services:
  ktrain_app:
    build: .
    container_name: ktrain_container
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    volumes:
      - .:/app
    ports:
      - "8888:8888"
    command: >
      jupyter lab --notebook-dir=/app --ip=0.0.0.0 --port=8888 --allow-root --no-browser

